<html>
<head>
<title>Error Capture in Python Programming Language</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python 编程语言中的错误捕获</h1>
<blockquote>原文：<a href="https://blog.devgenius.io/error-capture-in-python-programming-language-cdf9434a8c2b?source=collection_archive---------13-----------------------#2022-12-14">https://blog.devgenius.io/error-capture-in-python-programming-language-cdf9434a8c2b?source=collection_archive---------13-----------------------#2022-12-14</a></blockquote><div><div class="fc ib ic id ie if"/><div class="ig ih ii ij ik"><div class=""/><p id="d39d" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi ki translated">大家好！！！我们将讨论如何在 Python 中捕获错误。这是我在 Medium 上的第一篇英文帖子。我希望你会喜欢读它。所以让我们开始吧！！！</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="kw kx l"/></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">https://media.giphy.com/media/LPFmCBiTjEzcUeluCW/giphy.gif<a class="ae lc" href="https://media.giphy.com/media/LPFmCBiTjEzcUeluCW/giphy.gif" rel="noopener ugc nofollow" target="_blank"/></figcaption></figure><p id="97b0" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">当我们刚接触编码时，通常我们写的所有程序都基于一个共同的假设。也就是说，我们假设程序总是按照我们希望用户使用的方式来使用。例如，当我们编写一个添加数字的程序时，我们假设用户将总是输入数字数据。然而，尽管我们用心良苦，事情并不总是如我们所愿。例如，正如我们所说，如果程序是基于用户输入一个数字，我们不能确定用户将总是输入一个数字。</p><p id="4037" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">例如，想象我们编写一个这样的程序:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><p id="ca03" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">输出将如下所示:</p><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi le"><img src="../Images/a6699dc07fb3887853ec8e11b1c7e237.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*bfpFtlLUDO5PmMR7HTrvfw.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">代码的输出</figcaption></figure><p id="d18a" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在试图理解这些代码中的问题之前，让我们先看一下代码。</p><p id="2a89" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">如您所见，这里我们根据用户将要输入的数字进行平方根和平方运算。你知道，我们可以用这些代码中的**运算符来计算一个数的任何次方。例如，我们可以使用**运算符来计算 15⁸是什么:</p><pre class="kr ks kt ku gt ll lm ln lo aw lp bi"><span id="997e" class="lq lr in lm b gy ls lt l lu lv">&gt;&gt; 15 ** 8<br/>2562890625</span></pre><p id="0a89" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">如你所知，我们也可以用这个运算符来计算一个数的平方。因为毕竟，一个数的平方是这个数的 2 次方:</p><pre class="kr ks kt ku gt ll lm ln lo aw lp bi"><span id="92aa" class="lq lr in lm b gy ls lt l lu lv">&gt;&gt; 15 ** 2<br/>225</span></pre><p id="d470" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">同理，如果我们计算一个数的 0.5 次方，我们就求出了那个数的平方根(有意义:)。</p><pre class="kr ks kt ku gt ll lm ln lo aw lp bi"><span id="5813" class="lq lr in lm b gy ls lt l lu lv">&gt;&gt; 225 ** 2<br/>15</span></pre><p id="bbd2" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">现在我们已经检查了我们的代码，我们可以开始检查这个程序有什么问题。</p><p id="1dde" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">只要用户输入一个数值，这个程序就会运行。但是，如果用户输入的不是数字，而是其他东西，会发生什么呢？</p><p id="fb5f" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">例如，如果用户(有意或无意地)在上面的程序中输入一个字母而不是一个数字，他/她将得到如下错误:</p><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi le"><img src="../Images/9c5e81223c5eef5a260207fe080e0481.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Q7f2Pq_wseMluRqZiRwA7A.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">代码 2 的输出</figcaption></figure><p id="c3d2" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">你写的程序出现这样的错误是正常的。然而，从最终用户的角度来看，对于用户来说，更有意义的是得到一条消息，更清楚地解释什么是错的或者他/她做错了什么，而不是像上面这样的错误消息。上面的错误消息对程序员来说可能有意义，但对最终用户来说却完全无法理解！</p><p id="bc95" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">您的程序在运行时出现这样的错误是正常的。因为您试图执行的操作依赖于用户输入某种类型的数据。在这里，作为程序员，你的工作是预测程序在执行过程中可能出现的错误，并相应地在程序中采取一些预防措施。在本节中，我们将尝试了解如何采取这些预防措施。</p><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi lw"><img src="../Images/2e08cb8457fe372aa0f39c4fa7790557.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*k_8kzTsiQEA_Oy3CaWZaMg.png"/></div></div></figure><h2 id="afc0" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">错误类型</h2><p id="ba92" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">值得记住的是，“错误”的概念是多维的。特别是，我们需要从编程的角度来研究错误的概念意味着什么。</p><p id="2258" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在本节中，我们将在三个不同的标题下讨论错误:</p><ul class=""><li id="7d91" class="mt mu in jm b jn jo jr js jv mv jz mw kd mx kh my mz na nb bi translated">程序员错误</li><li id="0d46" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated">程序缺陷(Bug)</li><li id="7dcb" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated">例外</li></ul><p id="a3a8" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">首先说一下程序员错误。</p><p id="d987" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">程序员错误是由编写程序的人的粗心直接造成的明显错误。例如，以下代码包含一个程序员错误:</p><pre class="kr ks kt ku gt ll lm ln lo aw lp bi"><span id="2862" class="lq lr in lm b gy ls lt l lu lv">&gt;&gt; print "Hello World!"</span><span id="61d6" class="lq lr in lm b gy nh lt l lu lv">File "&lt;stdin&gt;", line 1<br/>   print "Hello World!"<br/>                         ^<br/>SyntaxError: invalid syntax</span></pre><p id="8572" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">这个错误消息中让我们感兴趣的部分在最后一句:SyntaxError。</p><p id="c22c" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">这些错误是由编程语言的一个特性的误用引起的，或者更简单地说，是由程序员的打字错误引起的。程序员的错误通常表现为语法错误。这些错误通常由程序员发现，并在程序到达用户之前由程序员纠正。与其他错误相比，这些类型的错误易于检测。因为这些错误会妨碍你的程序运行，所以不可能不注意到它们…</p><p id="a7cd" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">程序缺陷，也称为 bug，要复杂得多。有缺陷的程序通常运行时没有任何错误。然而，程序产生的输出并不是你所期望的。例如，您可能在程序中犯了一个公式错误。在这种情况下，您的程序运行起来好像没有任何问题，但是计算结果是错误的，因为公式不正确。例如，程序包含一个类似上面的缺陷:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><p id="911c" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在这个程序中，当用户输入数据时，我们的程序不会做加法，而是字符串连接，如下图所示。由于这样的程序在执行过程中不会出错，所以很难发现问题，尤其是在大型程序中。换句话说，你认为运行正常的程序实际上可能隐藏着一个错误。</p><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div class="gh gi ni"><img src="../Images/032cf66cda64cdc60e9243bde3498c84.png" data-original-src="https://miro.medium.com/v2/resize:fit:1308/format:webp/1*qFwlLXFjrnmkJ7lwy-W_Lg.png"/></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">代码的输出</figcaption></figure><p id="840b" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">同样地，不小心使用<strong class="jm io"> <em class="nj"> eval() </em> </strong>函数的程序也存在安全缺陷。换句话说，这样的程序有一个安全缺陷。正如我们所说的，程序缺陷是多维的，比我们在这里描述的要复杂得多。</p><p id="c2e7" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">先说第三类，例外。顾名思义，异常是程序执行过程中出现的异常情况。例如，让我们看看这个程序:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div class="gh gi ni"><img src="../Images/8abe54ac54944ba28284690c377d5ff2.png" data-original-src="https://miro.medium.com/v2/resize:fit:1308/format:webp/1*NoTYNzb_VO55IjdUeuTIag.png"/></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">除法程序的输出</figcaption></figure><p id="07d1" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">这里我们写了一个程序，将第一个数除以第二个数。这个程序可以做任何类型的除法。但是这里我们需要考虑两件事:</p><p id="94d4" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">用户可以输入非数字数据类型，而不是数字。例如，用户可以为第一个数字键入 10，为第二个数字键入“asd”。</p><p id="f57b" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">用户可以尝试将一个数除以 0。例如，用户可以为第一个数字写 12，为第二个数字写 0。</p><p id="9260" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在第一种情况下，我们的程序给出以下错误:</p><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi nk"><img src="../Images/fd206d2d65e65c2c26bd2f82b7bdac8b.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*CxXf91jWzmpLj1Bd6B4MzQ.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">第一个数字是 10，第二个是 asd</figcaption></figure><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi nk"><img src="../Images/88da80727287427b3ace57a8b75a65d1.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*wIRBKMLNANFlNuj_TqmYkg.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">第一个数字是 12，第二个是 0</figcaption></figure><p id="16a9" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">这里的问题是，您试图使用 int()函数将非数字数据转换成数字，并且您试图将一个数字除以 0。在数学中，数字不能被 0 整除。</p><p id="eb34" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">我们在这两个例子中看到的<strong class="jm io"> ValueError </strong>和<strong class="jm io"> ZeroDivisionError </strong>是例外。换句话说，当需要一个数字时，用户输入非数字数据或试图将一个数字除以 0 是一种异常情况，会导致我们编写的程序生成异常。</p><p id="5c38" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">由此，我们回顾了错误、bug 和异常之间的区别，但值得一提的是，这三个概念之间的区别是微妙的:这三个概念之间的区别是微妙的。换句话说，你可能会看到它们在很多地方互换使用。</p><h2 id="65ae" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">尝试…除了…</h2><p id="4dc9" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">在上一节中，我们讨论了错误和捕捉错误，但是我们如何捕捉它们呢？</p><p id="d494" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">Python 使用 try… except…块来捕捉错误。我们举个例子:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><p id="c0ff" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">我们知道，当我们想要将数据转换成数字时，如果用户输入字母值数据而不是数字值数据，我们的程序就会崩溃。因此，根据用户输入的数据类型，int(first_number)和 int(second_number)代码可能会产生错误。这就是为什么我们把这些代码放在 try 块中，因为我们知道它们会抛出一个错误。</p><p id="11e2" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">同样，我们知道，如果用户在数据转换过程中输入了不适当的数据，就会产生 ValueError 错误。因此，我们将在 except 块中写入的错误类型的名称将是 ValueError。因此，我们编写了下面几行代码来捕获 ValueError:</p><pre class="kr ks kt ku gt ll lm ln lo aw lp bi"><span id="2c8f" class="lq lr in lm b gy ls lt l lu lv">except ValueError:<br/>    print("Please enter only numeric values")</span></pre><p id="39f6" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">使用这段代码，我们为 Python 提供了以下命令:</p><p id="0889" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">如果在 try 块中指定的操作过程中遇到 ValueError，请忽略它，并且不显示通常向用户显示的错误信息。相反，向用户显示警告，请只输入数字！</p><p id="034b" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">现在让我们的代码在除以 0 时采取预防措施。当一个数被 0 整除时，Python 会抛出 ZeroDivisionError。那么我们可以写一个这样的代码:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><p id="0f68" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">正如你所看到的，我们试图在我们知道 Python 会抛出 ZeroDivisionError 的情况下捕捉这种类型的错误。这样，我们不会向用户显示无意义和复杂的错误信息，更糟糕的是，不会导致程序崩溃，而是产生更容易理解的信息。上面的代码还展示了如何在同一代码中捕捉两种不同的错误类型。</p><h2 id="6fe5" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">尝试…除了…作为…</h2><p id="9b0e" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">假设您希望向用户显示您编写的错误消息以及在出现错误时的原始错误消息。在这种情况下，以下结构会很有用:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><h2 id="7b0e" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">尝试…除了…别的…</h2><p id="7f04" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">如果用户输入字母而不是数字，我们会得到一个 ValueError 错误。我们用表达式 except ValueError:捕捉这个错误，并通过在错误发生时向用户显示一条消息来防止程序崩溃。但是我们知道，当我们运行这段代码时，ValueError 并不是 Python 能够给出的唯一错误。如果用户试图将一个数除以 0，Python 将抛出 ZeroDivisionError。</p><p id="e061" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">通过这种方式，我们可以捕获 ValueError 错误和 ZeroDivisionError 错误。这些代码的特殊之处在于 except…块是基于单个 try…块的。所以这里我们把所有的代码都塞进了一个 try…块。然后，在 except…块的帮助下，我们捕捉这个块中发生的任何错误。但是如果我们愿意，我们也可以选择将代码中给出的错误分组:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi nl"><img src="../Images/d0c622883f990d54912a6d1da59fb3da.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*iQQI9Fr-W0pFJ30zjLg9Xw.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">代码的输出</figcaption></figure><p id="fa2b" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">我们是这样做的:借助于第一个 try… except…块，我们首先用 int(input())函数检查来自用户的数据是否是一个数字。然后我们打开一个 else…块，在其中我们激活第二个 try… except…块。这里我们执行除法运算。如果用户在除法过程中输入数字 0，我们将借助 except ZeroDivisionError 语句来处理可能的错误。以这种方式编码的好处是，它帮助我们保持对错误的一些控制。感谢上面的代码，我们给出了一种“一次来一个！”错误消息。因此，在每个块中，我们只接收到我们期望接收到的错误。比如上面第一个 try…块中的转换操作只能返回 ValueError，而 else:块之后的 try…块中的操作只会返回 ZeroDivisionError。由于我们上面使用的结构，我们可以在适当的时候单独处理每个错误。相比之下，在本章开头的 try… except 块中，ValueError 和 ZeroDivisionError 都是可能的。因此，我们将所有错误压缩到一个 try…块中。这里，else:块解决了这种拥塞。</p><h2 id="1bc4" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">尝试…除了…最后…</h2><p id="8ed1" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">finally…块最重要的特性是，无论程序执行过程中是否出现错误，它都会被执行。如果程序中有一部分必须执行，您可以将该部分写在 finally…块中。</p><p id="3060" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">finally…块在文件操作中特别有用。</p><h2 id="8da1" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">上升</h2><p id="9199" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">有时，在我们编写的程序中，我们可能希望向用户显示“Python 风格”的错误消息，即使用户的操作在正常情况下不会产生错误。在这种情况下，Python 为我们提供了一个名为 raise 的语句。借助该语句，我们可以生成特定于情况的错误消息。让我们举个例子:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi nm"><img src="../Images/e3d531a3f2353900df36fa39fc7edea7.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*T9SI3kZhNTZC_rQEmFUpLA.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">代码的输出</figcaption></figure><p id="a46c" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在这里，如果用户输入数字 2，将向用户显示一条错误消息并退出程序。在这段代码中，我们使用了一般的错误消息异常。我们不能写任何想写的东西来代替异常。我们只能编写用 Python 定义的错误消息。例如名称错误、类型错误、零分错误、io 错误等…</p><h2 id="2dae" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">维护</h2><p id="d337" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">有时当我们在程序中犯了一个错误，我们可能很难发现它。我们可以通过使用 print 函数来找到这个错误，但是如果我们的程序在屏幕上打印了太多的内容，这可能会被忽略。在这种情况下，我们可以使用 assert 语句。assert 语句也是引发错误的一种快捷方式。但是，我们只能使用 assert 引发 AssertionError 类型的错误。通常使用 raise 会更好。正如我们所说，assert 用于快速识别代码中的错误。现在让我们想象我们有这样的代码:</p><figure class="kr ks kt ku gt kv"><div class="bz fp l di"><div class="ld kx l"/></div></figure><figure class="kr ks kt ku gt kv gh gi paragraph-image"><div role="button" tabindex="0" class="lf lg di lh bf li"><div class="gh gi nn"><img src="../Images/e4c6680187f0f5bdcea7bab7e1134657.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Xv8donnMPGir4bQl_a0QLA.png"/></div></div><figcaption class="ky kz gj gh gi la lb bd b be z dk translated">有空名称和没有空名称的输出</figcaption></figure><p id="d50f" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">我们可以使用 assert 编写如下代码:</p><pre class="kr ks kt ku gt ll lm ln lo aw lp bi"><span id="69de" class="lq lr in lm b gy ls lt l lu lv">name = input("What is yout name? ")<br/>assert len(name) != 0 , "Name section cannot be empty"<br/>print("Welcome to the game, " + name)</span></pre><p id="a774" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在这里，表达式可以是布尔值，即 True 或 False，也可以是可用于布尔值函数的对象(就像 if 一样)。因此，如果表达式的值为 True，我们的 assert 语句将不起作用，但如果为 False，它将起作用。换句话说，我们需要在断言表达式中写入我们希望为真的条件，以便它在为假时引发错误。</p></div><div class="ab cl no np hr nq" role="separator"><span class="nr bw bk ns nt nu"/><span class="nr bw bk ns nt nu"/><span class="nr bw bk ns nt"/></div><div class="ig ih ii ij ik"><h2 id="a9d6" class="lq lr in bd lx ly lz dn ma mb mc dp md jv me mf mg jz mh mi mj kd mk ml mm mn bi translated">摘要</h2><p id="f072" class="pw-post-body-paragraph jk jl in jm b jn mo jp jq jr mp jt ju jv mq jx jy jz mr kb kc kd ms kf kg kh ig bi translated">在了解了语法错误和异常之间的区别之后，您了解了在 Python 中引发、捕捉和管理异常的不同方法。您注意到了本文中的以下选项:</p><ul class=""><li id="a1c0" class="mt mu in jm b jn jo jr js jv mv jz mw kd mx kh my mz na nb bi translated">允许你在任何时候抛出一个异常。</li><li id="5ca0" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated"><code class="fe nv nw nx lm b">assert</code>使您能够验证是否满足某个条件，如果不满足就抛出异常。</li><li id="83a1" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated">在<code class="fe nv nw nx lm b">try</code>子句中，所有语句都被执行，直到遇到异常。</li><li id="5d01" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated"><code class="fe nv nw nx lm b">except</code>用于捕获和处理 try 子句中遇到的异常。</li><li id="5c64" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated"><code class="fe nv nw nx lm b">else</code>允许您编写只有在 try 子句中没有遇到异常时才运行的代码段。</li><li id="93ff" class="mt mu in jm b jn nc jr nd jv ne jz nf kd ng kh my mz na nb bi translated"><code class="fe nv nw nx lm b">finally</code>使您能够执行应该一直运行的代码段，不管之前是否遇到任何异常。</li></ul></div><div class="ab cl no np hr nq" role="separator"><span class="nr bw bk ns nt nu"/><span class="nr bw bk ns nt nu"/><span class="nr bw bk ns nt"/></div><div class="ig ih ii ij ik"><p id="d66f" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">在本文中，我们已经详细了解了如何在 python 中处理错误。谢谢你花时间阅读它。</p><p id="8ee1" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">如果您有任何问题或想要联系我，我所有的社交媒体账户都在下面的链接上。</p><div class="ny nz gp gr oa ob"><a href="https://turhancankargin.me/" rel="noopener  ugc nofollow" target="_blank"><div class="oc ab fo"><div class="od ab oe cl cj of"><h2 class="bd io gy z fp og fr fs oh fu fw im bi translated">图尔汗能卡金|家</h2><div class="oi l"><h3 class="bd b gy z fp og fr fs oh fu fw dk translated">这是图尔汗·坎·卡金的作品集。</h3></div><div class="oj l"><p class="bd b dl z fp og fr fs oh fu fw dk translated">turhancankargin.me</p></div></div><div class="ok l"><div class="ol l om on oo ok op lj ob"/></div></div></a></div><p id="c97c" class="pw-post-body-paragraph jk jl in jm b jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ig bi translated">来源:</p><div class="ny nz gp gr oa ob"><a href="https://realpython.com/python-exceptions/" rel="noopener  ugc nofollow" target="_blank"><div class="oc ab fo"><div class="od ab oe cl cj of"><h2 class="bd io gy z fp og fr fs oh fu fw im bi translated">Python 异常:介绍-真正的 Python</h2><div class="oi l"><h3 class="bd b gy z fp og fr fs oh fu fw dk translated">立即观看本教程有一个由真正的 Python 团队创建的相关视频课程。和书面的一起看…</h3></div><div class="oj l"><p class="bd b dl z fp og fr fs oh fu fw dk translated">realpython.com</p></div></div><div class="ok l"><div class="oq l om on oo ok op lj ob"/></div></div></a></div><div class="ny nz gp gr oa ob"><a href="https://python-istihza.yazbel.com/" rel="noopener  ugc nofollow" target="_blank"><div class="oc ab fo"><div class="od ab oe cl cj of"><h2 class="bd io gy z fp og fr fs oh fu fw im bi translated">Python 程序 lama Dili - Yazbel Python Belgeleri</h2><div class="oi l"><h3 class="bd b gy z fp og fr fs oh fu fw dk translated">如果您在笔记簿型论坛上提问，而不是发表评论，您可以更快地得到答案…</h3></div><div class="oj l"><p class="bd b dl z fp og fr fs oh fu fw dk translated">python 集成开发工具</p></div></div><div class="ok l"><div class="or l om on oo ok op lj ob"/></div></div></a></div></div></div>    
</body>
</html>